In [37]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import jinja2 as jinja

In [38]:
df = pd.read_csv('vacinados.csv' ,sep = ';' )
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3407298 entries, 0 to 3407297
Data columns (total 9 columns):
 #   Column           Dtype
---  ------           -----
 0   cpf              object
 1   nome             object
 2   sexo             object
 3   grupo            object
 4   vacina           object
 5   lote             object
 6   dose             float64
 7   data_vacinacao   object
 8   local_vacinacao  object
dtypes: float64(1), object(8)
memory usage: 234.0+ MB

               dose
count  3.407297e+06
mean   1.723100e+00
std    7.341606e-01
min    1.000000e+00
25%    1.000000e+00
50%    2.000000e+00
75%    2.000000e+00
max    4.000000e+00

In [39]:
df['grupo'].head()

0    TRABALHADORES INDUSTRIAIS E BANCÁRIOS
1    TRABALHADORES INDUSTRIAIS E BANCÁRIOS
2                   TRABALHADORES DA SAÚDE
3                   TRABALHADORES DA SAÚDE
4                   TRABALHADORES DA SAÚDE
Name: grupo, dtype: object

In [40]:
df_trabalhadores_Saude = df[df['grupo'] == 'TRABALHADORES DA SAÚDE']

,cpf,nome,sexo,grupo,vacina,lote,dose,data_vacinacao,local_vacinacao
2,***.886.964-**,AAMANDA MARIA FREIRE DA SILVA,FEMININO,TRABALHADORES DA SAÚDE,1 - CORONAVAC - SINOVAC (BUTANTAN),210043,2.0,2021-03-04,CENTRO DE VACINAÇÃO PARQUE DE EXPOSIÇÃO
3,***.886.964-**,AAMANDA MARIA FREIRE DA SILVA,FEMININO,TRABALHADORES DA SAÚDE,1 - CORONAVAC - SINOVAC (BUTANTAN),210016,1.0,2021-02-11,CENTRO DE VACINAÇÃO COMPAZ MIGUEL ARRAES
4,***.886.964-**,AAMANDA MARIA FREIRE DA SILVA,FEMININO,TRABALHADORES DA SAÚDE,3 - COMIRNATY (PFIZER),32010BD,3.0,2021-10-07,CENTRO DE VACINAÇÃO UNINASSAU
15,***.326.204-**,AARÃO GONÇALVES DE OLIVEIRA BARRETO,MASCULINO,TRABALHADORES DA SAÚDE,3 - COMIRNATY (PFIZER),31065BD,3.0,2021-10-02,CENTRO DE VACINAÇÃO UFRPE - UNIVERSIDADE RURAL
28,***.988.494-**,AARNON PRESLEY XAVIER,MASCULINO,TRABALHADORES DA SAÚDE,2 - CHADOX1NCOV-19 - OXFORD/ASTRAZENECA (FIOCRUZ),216VCD215WA,2.0,2021-08-18,CENTRO DE VACINAÇÃO - DNOCS

In [41]:
df_local_trabalhador_Saude = df_trabalhadores_Saude[['local_vacinacao', 'grupo', 'sexo', 'dose']]
df_local_trabalhador_Saude.head()

,local_vacinacao,grupo,sexo,dose
2,CENTRO DE VACINAÇÃO PARQUE DE EXPOSIÇÃO,TRABALHADORES DA SAÚDE,FEMININO,2.0
3,CENTRO DE VACINAÇÃO COMPAZ MIGUEL ARRAES,TRABALHADORES DA SAÚDE,FEMININO,1.0
4,CENTRO DE VACINAÇÃO UNINASSAU,TRABALHADORES DA SAÚDE,FEMININO,3.0
15,CENTRO DE VACINAÇÃO UFRPE - UNIVERSIDADE RURAL,TRABALHADORES DA SAÚDE,MASCULINO,3.0
28,CENTRO DE VACINAÇÃO - DNOCS,TRABALHADORES DA SAÚDE,MASCULINO,2.0

In [42]:
resultado_local = df_local_trabalhador_Saude.groupby(['local_vacinacao']).size().reset_index(name='contagem')
resultado_genero = df_local_trabalhador_Saude.groupby(['sexo']).size().reset_index(name='contagem')
resultado_local_max = resultado_local.loc[resultado_local.groupby('local_vacinacao')['contagem'].idxmax()]
resultado_genero_max = resultado_genero.loc[resultado_genero.groupby('sexo')['contagem'].idxmax()]
print(resultado_local_max)

                                    local_vacinacao  contagem
0       CENTRO DE SAÚDE BIDU KRAUSE (UNIDADE MÓVEL)         1
1     POLICLÍNICA GOUVEIA DE BARROS (UNIDADE MÓVEL)        23
2                       CENTRO DE SAÚDE BIDU KRAUSE        61
3                        CENTRO DE SAÚDE BRUNO MAIA        59
4        CENTRO DE SAÚDE BRUNO MAIA (UNIDADE MÓVEL)         1
..                                              ...       ...
128              UPINHA VILA ARRAES (UNIDADE MÓVEL)        15
129                   USF COQUE BERILO PERNAMBUCANO        56
130                            USF SÍTIO DOS PINTOS        72
131            USF SÍTIO DOS PINTOS (UNIDADE MÓVEL)         1
132                    VACINAÇÃO ESCOLAR ITINERANTE        81

[133 rows x 2 columns]

In [48]:
local_max = resultado_local.loc[resultado_local_max['contagem'].idxmax()]
local_min = resultado_local.loc[resultado_local_max['contagem'].idxmin()]
genero_max = resultado_genero.loc[resultado_genero_max['contagem'].idxmax()]

tabela_comparativa = pd.DataFrame({
    'Local que mais se vacinou': [local_max['local_vacinacao']],
    'Gênero que mais se vacinou': [genero_max['sexo']],
    'Contagem do Local': [local_max['contagem']],
    'Contagem do Gênero que mais se vacinou no geral': [genero_max['contagem']]
})
tabela_estilizada = tabela_comparativa.style \
    .set_table_attributes('style="width: 80%; margin: auto;"') \
    .set_caption("Tabela Comparativa de Vacinação da Covid-19 dos trabalhadores da Área de Saúde:") \
    .highlight_max(color='blue', axis=0) \
    .highlight_min(color='black', axis=0) \
    .set_properties(**{'text-align': 'center'}) \
    .set_table_styles([{
        'selector': 'th',
        'props': [('background-color', 'black'), ('font-size', '14px')]
    }])
print("Tabela Comparativa:")
tabela_estilizada

Tabela Comparativa: